#创建非登陆用户
- name: Create Mattermost System User
  user:
      name: mattermost 
      create_home: no 
      shell: /usr/sbin/nologin
      
#创建可登陆用户jetty，并在home下创建用户目录
- name: Create jetty User
  user:
    name: jetty
    shell: /usr/bin/bash
    create_home: yes
